org: egonuler
app: techtimes-api
service: auth-srv

frameworkVersion: '2'

provider:
  name: aws
  stage: ${opt:stage}
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  api:
    handler: src/app.slsApp
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

custom:
  dotenv:
    path: .././.env.${opt:stage}

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin
