org: egonuler
app: techtimes-api
service: cms-srv

frameworkVersion: '2'

provider:
  name: aws
  stage: dev
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  api:
    handler: src/app.slsApp
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

custom:
  dotenv:
    path: .././.env.development

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
